/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RoomType = IDL.Variant({
  'bedroom' : IDL.Null,
  'bathroom' : IDL.Null,
  'garage' : IDL.Null,
  'kitchen' : IDL.Null,
  'livingRoom' : IDL.Null,
});
export const Room = IDL.Record({
  'size' : IDL.Tuple(IDL.Nat, IDL.Nat),
  'position' : IDL.Tuple(IDL.Int, IDL.Int),
  'roomType' : RoomType,
});
export const FloorPlan = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'rooms' : IDL.Vec(Room),
});

export const idlService = IDL.Service({
  'deletePlan' : IDL.Func([IDL.Nat], [], []),
  'getAllPlans' : IDL.Func([], [IDL.Vec(FloorPlan)], ['query']),
  'getPlan' : IDL.Func([IDL.Nat], [FloorPlan], ['query']),
  'savePlan' : IDL.Func([IDL.Text, IDL.Vec(Room)], [IDL.Nat], []),
  'updatePlan' : IDL.Func([IDL.Nat, IDL.Text, IDL.Vec(Room)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RoomType = IDL.Variant({
    'bedroom' : IDL.Null,
    'bathroom' : IDL.Null,
    'garage' : IDL.Null,
    'kitchen' : IDL.Null,
    'livingRoom' : IDL.Null,
  });
  const Room = IDL.Record({
    'size' : IDL.Tuple(IDL.Nat, IDL.Nat),
    'position' : IDL.Tuple(IDL.Int, IDL.Int),
    'roomType' : RoomType,
  });
  const FloorPlan = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'rooms' : IDL.Vec(Room),
  });
  
  return IDL.Service({
    'deletePlan' : IDL.Func([IDL.Nat], [], []),
    'getAllPlans' : IDL.Func([], [IDL.Vec(FloorPlan)], ['query']),
    'getPlan' : IDL.Func([IDL.Nat], [FloorPlan], ['query']),
    'savePlan' : IDL.Func([IDL.Text, IDL.Vec(Room)], [IDL.Nat], []),
    'updatePlan' : IDL.Func([IDL.Nat, IDL.Text, IDL.Vec(Room)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };