/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Room {
    size: [bigint, bigint];
    position: [bigint, bigint];
    roomType: RoomType;
}
export interface FloorPlan {
    id: bigint;
    name: string;
    rooms: Array<Room>;
}
export enum RoomType {
    bedroom = "bedroom",
    bathroom = "bathroom",
    garage = "garage",
    kitchen = "kitchen",
    livingRoom = "livingRoom"
}
export interface backendInterface {
    deletePlan(id: bigint): Promise<void>;
    getAllPlans(): Promise<Array<FloorPlan>>;
    getPlan(id: bigint): Promise<FloorPlan>;
    savePlan(name: string, rooms: Array<Room>): Promise<bigint>;
    updatePlan(id: bigint, name: string, rooms: Array<Room>): Promise<void>;
}
import type { FloorPlan as _FloorPlan, Room as _Room, RoomType as _RoomType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async deletePlan(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePlan(arg0);
            return result;
        }
    }
    async getAllPlans(): Promise<Array<FloorPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlans();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlans();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlan(arg0: bigint): Promise<FloorPlan> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlan(arg0);
                return from_candid_FloorPlan_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlan(arg0);
            return from_candid_FloorPlan_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async savePlan(arg0: string, arg1: Array<Room>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.savePlan(arg0, to_candid_vec_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePlan(arg0, to_candid_vec_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePlan(arg0: bigint, arg1: string, arg2: Array<Room>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlan(arg0, arg1, to_candid_vec_n9(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlan(arg0, arg1, to_candid_vec_n9(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_FloorPlan_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FloorPlan): FloorPlan {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_RoomType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoomType): RoomType {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Room_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Room): Room {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    rooms: Array<_Room>;
}): {
    id: bigint;
    name: string;
    rooms: Array<Room>;
} {
    return {
        id: value.id,
        name: value.name,
        rooms: from_candid_vec_n4(_uploadFile, _downloadFile, value.rooms)
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    size: [bigint, bigint];
    position: [bigint, bigint];
    roomType: _RoomType;
}): {
    size: [bigint, bigint];
    position: [bigint, bigint];
    roomType: RoomType;
} {
    return {
        size: value.size,
        position: value.position,
        roomType: from_candid_RoomType_n7(_uploadFile, _downloadFile, value.roomType)
    };
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bedroom: null;
} | {
    bathroom: null;
} | {
    garage: null;
} | {
    kitchen: null;
} | {
    livingRoom: null;
}): RoomType {
    return "bedroom" in value ? RoomType.bedroom : "bathroom" in value ? RoomType.bathroom : "garage" in value ? RoomType.garage : "kitchen" in value ? RoomType.kitchen : "livingRoom" in value ? RoomType.livingRoom : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FloorPlan>): Array<FloorPlan> {
    return value.map((x)=>from_candid_FloorPlan_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Room>): Array<Room> {
    return value.map((x)=>from_candid_Room_n5(_uploadFile, _downloadFile, x));
}
function to_candid_RoomType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomType): _RoomType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_Room_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Room): _Room {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    size: [bigint, bigint];
    position: [bigint, bigint];
    roomType: RoomType;
}): {
    size: [bigint, bigint];
    position: [bigint, bigint];
    roomType: _RoomType;
} {
    return {
        size: value.size,
        position: value.position,
        roomType: to_candid_RoomType_n12(_uploadFile, _downloadFile, value.roomType)
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomType): {
    bedroom: null;
} | {
    bathroom: null;
} | {
    garage: null;
} | {
    kitchen: null;
} | {
    livingRoom: null;
} {
    return value == RoomType.bedroom ? {
        bedroom: null
    } : value == RoomType.bathroom ? {
        bathroom: null
    } : value == RoomType.garage ? {
        garage: null
    } : value == RoomType.kitchen ? {
        kitchen: null
    } : value == RoomType.livingRoom ? {
        livingRoom: null
    } : value;
}
function to_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Room>): Array<_Room> {
    return value.map((x)=>to_candid_Room_n10(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
